local p=game.Players.LocalPlayer
local g=gethui and gethui() or p.PlayerGui
for _,v in pairs(g:GetChildren())do if v.Name=="A"then v:Destroy()end end
local sg=Instance.new("ScreenGui",g)sg.Name="A"sg.ResetOnSpawn=false
local b=Instance.new("TextButton",sg)b.Size=UDim2.new(0,60,0,60)b.Position=UDim2.new(0.05,0,0.5,0)b.Text="A"b.BackgroundColor3=Color3.fromRGB(255,0,0)b.TextSize=28 b.Active=true b.Draggable=true Instance.new("UICorner",b).CornerRadius=UDim.new(1,0)
local m=Instance.new("Frame",sg)m.Size=UDim2.new(0,200,0,320)m.Position=UDim2.new(0.5,-100,0.5,-160)m.BackgroundColor3=Color3.fromRGB(18,18,18)Instance.new("UICorner",m).CornerRadius=UDim.new(0,10)
local function mk(t,y,c,f)local x=Instance.new("TextButton",m)x.Size=UDim2.new(0.9,0,0,28)x.Position=UDim2.new(0.05,0,0,y)x.Text=t x.BackgroundColor3=c x.TextColor3=Color3.new(1,1,1)x.Font=Enum.Font.GothamBold x.TextSize=11 Instance.new("UICorner",x).CornerRadius=UDim.new(0,6)x.Activated:Connect(function()f(x)end)return x endlocal speedOn=false mk("SPEED 2000 OFF",5,Color3.fromRGB(255,0,0),function(x)speedOn=not speedOn if speedOn then p.Character.Humanoid.UseJumpPower=false p.Character.Humanoid.JumpHeight=100 p.Character.Humanoid.WalkSpeed=2000 x.Text="SPEED 2000 ON" x.BackgroundColor3=Color3.fromRGB(0,200,0) else p.Character.Humanoid.WalkSpeed=16 p.Character.Humanoid.JumpHeight=7.2 x.Text="SPEED 2000 OFF" x.BackgroundColor3=Color3.fromRGB(255,0,0) end end)
local antiOn=false mk("ANTI JEFE OFF",37,Color3.fromRGB(0,100,200),function(x)antiOn=not antiOn x.Text=antiOn and"ANTI JEFE ON"or"ANTI JEFE OFF" x.BackgroundColor3=antiOn and Color3.fromRGB(0,200,0) or Color3.fromRGB(0,100,200) end)
local a=false mk("AUTO ROBAR OFF",69,Color3.fromRGB(150,0,150),function(x)a=not a x.Text=a and"AUTO ROBAR ON"or"AUTO ROBAR OFF" x.BackgroundColor3=a and Color3.fromRGB(0,200,0) or Color3.fromRGB(150,0,150) end)
local k=false mk("AUTO BATE OFF",101,Color3.fromRGB(255,100,0),function(x)k=not k x.Text=k and"AUTO BATE ON"or"AUTO BATE OFF" x.BackgroundColor3=k and Color3.fromRGB(0,200,0) or Color3.fromRGB(255,100,0) end)
local flyOn=false local bv,bg mk("FLY OFF",133,Color3.fromRGB(0,150,150),function(x)flyOn=not flyOn x.Text=flyOn and"FLY ON"or"FLY OFF" x.BackgroundColor3=flyOn and Color3.fromRGB(0,200,0) or Color3.fromRGB(0,150,150) if flyOn then bv=Instance.new("BodyVelocity",p.Character.HumanoidRootPart)bv.Velocity=Vector3.new(0,0,0)bv.MaxForce=Vector3.new(9e9,9e9,9e9) bg=Instance.new("BodyGyro",p.Character.HumanoidRootPart)bg.MaxTorque=Vector3.new(9e9,9e9,9e9)bg.P=9e4 else if bv then bv:Destroy()end if bg then bg:Destroy()end end end)
local espOn=false mk("ESP OFF",165,Color3.fromRGB(0,100,0),function(x)espOn=not espOn x.Text=espOn and"ESP ON"or"ESP OFF" x.BackgroundColor3=espOn and Color3.fromRGB(0,200,0) or Color3.fromRGB(0,100,0) for _,pl in pairs(game.Players:GetPlayers())do if pl~=p and pl.Character then if espOn then if not pl.Character:FindFirstChild("ESP")then local hl=Instance.new("Highlight",pl.Character)hl.Name="ESP"hl.FillColor=Color3.fromRGB(255,0,0)end else if pl.Character:FindFirstChild("ESP")then pl.Character.ESP:Destroy()end end end end end)
local noclipOn=false mk("NOCLIP OFF",197,Color3.fromRGB(100,100,0),function(x)noclipOn=not noclipOn x.Text=noclipOn and"NOCLIP ON"or"NOCLIP OFF" x.BackgroundColor3=noclipOn and Color3.fromRGB(0,200,0) or Color3.fromRGB(100,100,0) end)
local infOn=false mk("INF SALTO OFF",229,Color3.fromRGB(0,80,80),function(x)infOn=not infOn x.Text=infOn and"INF SALTO ON"or"INF SALTO OFF" x.BackgroundColor3=infOn and Color3.fromRGB(0,200,0) or Color3.fromRGB(0,80,80) game:GetService("UserInputService").JumpRequest:Connect(function()if infOn and p.Character then p.Character.Humanoid:ChangeState(Enum.HumanoidStateType.Jumping)end end)end)
mk("CERRAR MENU",270,Color3.fromRGB(80,0,0),function()m.Visible=false end) b.Activated:Connect(function()m.Visible=not m.Visible end)
task.spawn(function()while task.wait(0.2)do if(antiOn or noclipOn)and p.Character then for _,v in pairs(p.Character:GetDescendants())do if v:IsA("BasePart")then v.CanCollide=false end end end end end)
task.spawn(function()while task.wait(0.2)do if a then for _,v in pairs(workspace:GetDescendants())do if v:IsA("ProximityPrompt")and p.Character and p.Character:FindFirstChild("HumanoidRootPart")and(v.Parent.Position-p.Character.HumanoidRootPart.Position).Magnitude<15 then fireproximityprompt(v)end end end end end)
task.spawn(function()while task.wait(0.1)do if k then for _,pl in pairs(game.Players:GetPlayers())do if pl~=p and pl.Character and pl.Character:FindFirstChild("HumanoidRootPart")and(p.Character.HumanoidRootPart.Position-pl.Character.HumanoidRootPart.Position).Magnitude<12 then for _,t in pairs(p.Character:GetChildren())do if t:IsA("Tool")then t:Activate()end end end end end end end)